import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/** Persisted inputs and the structured plan generated by Groq. */
export const festivalPlans = mysqlTable("festivalPlans", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  festival: varchar("festival", { length: 120 }).notNull(),
  city: varchar("city", { length: 160 }).notNull(),
  familySize: int("familySize").notNull(),
  budget: int("budget").notNull(),
  language: varchar("language", { length: 64 }).notNull(),
  preferences: text("preferences"),
  planJson: text("planJson").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type FestivalPlan = typeof festivalPlans.$inferSelect;
export type InsertFestivalPlan = typeof festivalPlans.$inferInsert;
